#!/bin/bash
if [ -n "$BASH_VERSION" ]; then
  if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
  fi
fi

if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

export PATH=$PATH:$HOME/.rbenv/bin:/opt/node/bin:/vagrant/node_modules/.bin/

source ~/.autoenv/activate.sh

eval "$(rbenv init -)"
